# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mttchpmn07/geant4/geant4.9.6.p01/examples/novice/geant_sim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mttchpmn07/geant4/geant4.9.6.p01/examples/novice/geant_sim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mttchpmn07/geant4/geant4.9.6.p01/examples/novice/geant_sim/CMakeFiles /home/mttchpmn07/geant4/geant4.9.6.p01/examples/novice/geant_sim/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mttchpmn07/geant4/geant4.9.6.p01/examples/novice/geant_sim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named N06

# Build rule for target.
N06: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 N06
.PHONY : N06

# fast build rule for target.
N06/fast:
	$(MAKE) -f CMakeFiles/N06.dir/build.make CMakeFiles/N06.dir/build
.PHONY : N06/fast

#=============================================================================
# Target rules for targets named exampleN06

# Build rule for target.
exampleN06: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exampleN06
.PHONY : exampleN06

# fast build rule for target.
exampleN06/fast:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/build
.PHONY : exampleN06/fast

exampleN06.o: exampleN06.cc.o
.PHONY : exampleN06.o

# target to build an object file
exampleN06.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/exampleN06.cc.o
.PHONY : exampleN06.cc.o

exampleN06.i: exampleN06.cc.i
.PHONY : exampleN06.i

# target to preprocess a source file
exampleN06.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/exampleN06.cc.i
.PHONY : exampleN06.cc.i

exampleN06.s: exampleN06.cc.s
.PHONY : exampleN06.s

# target to generate assembly for a file
exampleN06.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/exampleN06.cc.s
.PHONY : exampleN06.cc.s

src/CsI_SD.o: src/CsI_SD.cc.o
.PHONY : src/CsI_SD.o

# target to build an object file
src/CsI_SD.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/CsI_SD.cc.o
.PHONY : src/CsI_SD.cc.o

src/CsI_SD.i: src/CsI_SD.cc.i
.PHONY : src/CsI_SD.i

# target to preprocess a source file
src/CsI_SD.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/CsI_SD.cc.i
.PHONY : src/CsI_SD.cc.i

src/CsI_SD.s: src/CsI_SD.cc.s
.PHONY : src/CsI_SD.s

# target to generate assembly for a file
src/CsI_SD.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/CsI_SD.cc.s
.PHONY : src/CsI_SD.cc.s

src/CsI_SDHit.o: src/CsI_SDHit.cc.o
.PHONY : src/CsI_SDHit.o

# target to build an object file
src/CsI_SDHit.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/CsI_SDHit.cc.o
.PHONY : src/CsI_SDHit.cc.o

src/CsI_SDHit.i: src/CsI_SDHit.cc.i
.PHONY : src/CsI_SDHit.i

# target to preprocess a source file
src/CsI_SDHit.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/CsI_SDHit.cc.i
.PHONY : src/CsI_SDHit.cc.i

src/CsI_SDHit.s: src/CsI_SDHit.cc.s
.PHONY : src/CsI_SDHit.s

# target to generate assembly for a file
src/CsI_SDHit.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/CsI_SDHit.cc.s
.PHONY : src/CsI_SDHit.cc.s

src/EventAction.o: src/EventAction.cc.o
.PHONY : src/EventAction.o

# target to build an object file
src/EventAction.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/EventAction.cc.o
.PHONY : src/EventAction.cc.o

src/EventAction.i: src/EventAction.cc.i
.PHONY : src/EventAction.i

# target to preprocess a source file
src/EventAction.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/EventAction.cc.i
.PHONY : src/EventAction.cc.i

src/EventAction.s: src/EventAction.cc.s
.PHONY : src/EventAction.s

# target to generate assembly for a file
src/EventAction.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/EventAction.cc.s
.PHONY : src/EventAction.cc.s

src/ExN06DetectorConstruction.o: src/ExN06DetectorConstruction.cc.o
.PHONY : src/ExN06DetectorConstruction.o

# target to build an object file
src/ExN06DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06DetectorConstruction.cc.o
.PHONY : src/ExN06DetectorConstruction.cc.o

src/ExN06DetectorConstruction.i: src/ExN06DetectorConstruction.cc.i
.PHONY : src/ExN06DetectorConstruction.i

# target to preprocess a source file
src/ExN06DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06DetectorConstruction.cc.i
.PHONY : src/ExN06DetectorConstruction.cc.i

src/ExN06DetectorConstruction.s: src/ExN06DetectorConstruction.cc.s
.PHONY : src/ExN06DetectorConstruction.s

# target to generate assembly for a file
src/ExN06DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06DetectorConstruction.cc.s
.PHONY : src/ExN06DetectorConstruction.cc.s

src/ExN06EventAction.o: src/ExN06EventAction.cc.o
.PHONY : src/ExN06EventAction.o

# target to build an object file
src/ExN06EventAction.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06EventAction.cc.o
.PHONY : src/ExN06EventAction.cc.o

src/ExN06EventAction.i: src/ExN06EventAction.cc.i
.PHONY : src/ExN06EventAction.i

# target to preprocess a source file
src/ExN06EventAction.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06EventAction.cc.i
.PHONY : src/ExN06EventAction.cc.i

src/ExN06EventAction.s: src/ExN06EventAction.cc.s
.PHONY : src/ExN06EventAction.s

# target to generate assembly for a file
src/ExN06EventAction.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06EventAction.cc.s
.PHONY : src/ExN06EventAction.cc.s

src/ExN06PMTHit.o: src/ExN06PMTHit.cc.o
.PHONY : src/ExN06PMTHit.o

# target to build an object file
src/ExN06PMTHit.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PMTHit.cc.o
.PHONY : src/ExN06PMTHit.cc.o

src/ExN06PMTHit.i: src/ExN06PMTHit.cc.i
.PHONY : src/ExN06PMTHit.i

# target to preprocess a source file
src/ExN06PMTHit.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PMTHit.cc.i
.PHONY : src/ExN06PMTHit.cc.i

src/ExN06PMTHit.s: src/ExN06PMTHit.cc.s
.PHONY : src/ExN06PMTHit.s

# target to generate assembly for a file
src/ExN06PMTHit.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PMTHit.cc.s
.PHONY : src/ExN06PMTHit.cc.s

src/ExN06PMTSD.o: src/ExN06PMTSD.cc.o
.PHONY : src/ExN06PMTSD.o

# target to build an object file
src/ExN06PMTSD.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PMTSD.cc.o
.PHONY : src/ExN06PMTSD.cc.o

src/ExN06PMTSD.i: src/ExN06PMTSD.cc.i
.PHONY : src/ExN06PMTSD.i

# target to preprocess a source file
src/ExN06PMTSD.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PMTSD.cc.i
.PHONY : src/ExN06PMTSD.cc.i

src/ExN06PMTSD.s: src/ExN06PMTSD.cc.s
.PHONY : src/ExN06PMTSD.s

# target to generate assembly for a file
src/ExN06PMTSD.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PMTSD.cc.s
.PHONY : src/ExN06PMTSD.cc.s

src/ExN06PhysicListMessenger.o: src/ExN06PhysicListMessenger.cc.o
.PHONY : src/ExN06PhysicListMessenger.o

# target to build an object file
src/ExN06PhysicListMessenger.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PhysicListMessenger.cc.o
.PHONY : src/ExN06PhysicListMessenger.cc.o

src/ExN06PhysicListMessenger.i: src/ExN06PhysicListMessenger.cc.i
.PHONY : src/ExN06PhysicListMessenger.i

# target to preprocess a source file
src/ExN06PhysicListMessenger.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PhysicListMessenger.cc.i
.PHONY : src/ExN06PhysicListMessenger.cc.i

src/ExN06PhysicListMessenger.s: src/ExN06PhysicListMessenger.cc.s
.PHONY : src/ExN06PhysicListMessenger.s

# target to generate assembly for a file
src/ExN06PhysicListMessenger.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PhysicListMessenger.cc.s
.PHONY : src/ExN06PhysicListMessenger.cc.s

src/ExN06PhysicsList.o: src/ExN06PhysicsList.cc.o
.PHONY : src/ExN06PhysicsList.o

# target to build an object file
src/ExN06PhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PhysicsList.cc.o
.PHONY : src/ExN06PhysicsList.cc.o

src/ExN06PhysicsList.i: src/ExN06PhysicsList.cc.i
.PHONY : src/ExN06PhysicsList.i

# target to preprocess a source file
src/ExN06PhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PhysicsList.cc.i
.PHONY : src/ExN06PhysicsList.cc.i

src/ExN06PhysicsList.s: src/ExN06PhysicsList.cc.s
.PHONY : src/ExN06PhysicsList.s

# target to generate assembly for a file
src/ExN06PhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PhysicsList.cc.s
.PHONY : src/ExN06PhysicsList.cc.s

src/ExN06PrimaryGeneratorAction.o: src/ExN06PrimaryGeneratorAction.cc.o
.PHONY : src/ExN06PrimaryGeneratorAction.o

# target to build an object file
src/ExN06PrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PrimaryGeneratorAction.cc.o
.PHONY : src/ExN06PrimaryGeneratorAction.cc.o

src/ExN06PrimaryGeneratorAction.i: src/ExN06PrimaryGeneratorAction.cc.i
.PHONY : src/ExN06PrimaryGeneratorAction.i

# target to preprocess a source file
src/ExN06PrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PrimaryGeneratorAction.cc.i
.PHONY : src/ExN06PrimaryGeneratorAction.cc.i

src/ExN06PrimaryGeneratorAction.s: src/ExN06PrimaryGeneratorAction.cc.s
.PHONY : src/ExN06PrimaryGeneratorAction.s

# target to generate assembly for a file
src/ExN06PrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PrimaryGeneratorAction.cc.s
.PHONY : src/ExN06PrimaryGeneratorAction.cc.s

src/ExN06PrimaryGeneratorMessenger.o: src/ExN06PrimaryGeneratorMessenger.cc.o
.PHONY : src/ExN06PrimaryGeneratorMessenger.o

# target to build an object file
src/ExN06PrimaryGeneratorMessenger.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PrimaryGeneratorMessenger.cc.o
.PHONY : src/ExN06PrimaryGeneratorMessenger.cc.o

src/ExN06PrimaryGeneratorMessenger.i: src/ExN06PrimaryGeneratorMessenger.cc.i
.PHONY : src/ExN06PrimaryGeneratorMessenger.i

# target to preprocess a source file
src/ExN06PrimaryGeneratorMessenger.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PrimaryGeneratorMessenger.cc.i
.PHONY : src/ExN06PrimaryGeneratorMessenger.cc.i

src/ExN06PrimaryGeneratorMessenger.s: src/ExN06PrimaryGeneratorMessenger.cc.s
.PHONY : src/ExN06PrimaryGeneratorMessenger.s

# target to generate assembly for a file
src/ExN06PrimaryGeneratorMessenger.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06PrimaryGeneratorMessenger.cc.s
.PHONY : src/ExN06PrimaryGeneratorMessenger.cc.s

src/ExN06RunAction.o: src/ExN06RunAction.cc.o
.PHONY : src/ExN06RunAction.o

# target to build an object file
src/ExN06RunAction.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06RunAction.cc.o
.PHONY : src/ExN06RunAction.cc.o

src/ExN06RunAction.i: src/ExN06RunAction.cc.i
.PHONY : src/ExN06RunAction.i

# target to preprocess a source file
src/ExN06RunAction.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06RunAction.cc.i
.PHONY : src/ExN06RunAction.cc.i

src/ExN06RunAction.s: src/ExN06RunAction.cc.s
.PHONY : src/ExN06RunAction.s

# target to generate assembly for a file
src/ExN06RunAction.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06RunAction.cc.s
.PHONY : src/ExN06RunAction.cc.s

src/ExN06StackingAction.o: src/ExN06StackingAction.cc.o
.PHONY : src/ExN06StackingAction.o

# target to build an object file
src/ExN06StackingAction.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06StackingAction.cc.o
.PHONY : src/ExN06StackingAction.cc.o

src/ExN06StackingAction.i: src/ExN06StackingAction.cc.i
.PHONY : src/ExN06StackingAction.i

# target to preprocess a source file
src/ExN06StackingAction.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06StackingAction.cc.i
.PHONY : src/ExN06StackingAction.cc.i

src/ExN06StackingAction.s: src/ExN06StackingAction.cc.s
.PHONY : src/ExN06StackingAction.s

# target to generate assembly for a file
src/ExN06StackingAction.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06StackingAction.cc.s
.PHONY : src/ExN06StackingAction.cc.s

src/ExN06SteppingVerbose.o: src/ExN06SteppingVerbose.cc.o
.PHONY : src/ExN06SteppingVerbose.o

# target to build an object file
src/ExN06SteppingVerbose.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06SteppingVerbose.cc.o
.PHONY : src/ExN06SteppingVerbose.cc.o

src/ExN06SteppingVerbose.i: src/ExN06SteppingVerbose.cc.i
.PHONY : src/ExN06SteppingVerbose.i

# target to preprocess a source file
src/ExN06SteppingVerbose.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06SteppingVerbose.cc.i
.PHONY : src/ExN06SteppingVerbose.cc.i

src/ExN06SteppingVerbose.s: src/ExN06SteppingVerbose.cc.s
.PHONY : src/ExN06SteppingVerbose.s

# target to generate assembly for a file
src/ExN06SteppingVerbose.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06SteppingVerbose.cc.s
.PHONY : src/ExN06SteppingVerbose.cc.s

src/ExN06UserEventInformation.o: src/ExN06UserEventInformation.cc.o
.PHONY : src/ExN06UserEventInformation.o

# target to build an object file
src/ExN06UserEventInformation.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06UserEventInformation.cc.o
.PHONY : src/ExN06UserEventInformation.cc.o

src/ExN06UserEventInformation.i: src/ExN06UserEventInformation.cc.i
.PHONY : src/ExN06UserEventInformation.i

# target to preprocess a source file
src/ExN06UserEventInformation.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06UserEventInformation.cc.i
.PHONY : src/ExN06UserEventInformation.cc.i

src/ExN06UserEventInformation.s: src/ExN06UserEventInformation.cc.s
.PHONY : src/ExN06UserEventInformation.s

# target to generate assembly for a file
src/ExN06UserEventInformation.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ExN06UserEventInformation.cc.s
.PHONY : src/ExN06UserEventInformation.cc.s

src/Si_SD.o: src/Si_SD.cc.o
.PHONY : src/Si_SD.o

# target to build an object file
src/Si_SD.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/Si_SD.cc.o
.PHONY : src/Si_SD.cc.o

src/Si_SD.i: src/Si_SD.cc.i
.PHONY : src/Si_SD.i

# target to preprocess a source file
src/Si_SD.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/Si_SD.cc.i
.PHONY : src/Si_SD.cc.i

src/Si_SD.s: src/Si_SD.cc.s
.PHONY : src/Si_SD.s

# target to generate assembly for a file
src/Si_SD.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/Si_SD.cc.s
.PHONY : src/Si_SD.cc.s

src/Si_SDHit.o: src/Si_SDHit.cc.o
.PHONY : src/Si_SDHit.o

# target to build an object file
src/Si_SDHit.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/Si_SDHit.cc.o
.PHONY : src/Si_SDHit.cc.o

src/Si_SDHit.i: src/Si_SDHit.cc.i
.PHONY : src/Si_SDHit.i

# target to preprocess a source file
src/Si_SDHit.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/Si_SDHit.cc.i
.PHONY : src/Si_SDHit.cc.i

src/Si_SDHit.s: src/Si_SDHit.cc.s
.PHONY : src/Si_SDHit.s

# target to generate assembly for a file
src/Si_SDHit.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/Si_SDHit.cc.s
.PHONY : src/Si_SDHit.cc.s

src/ThickScintHit.o: src/ThickScintHit.cc.o
.PHONY : src/ThickScintHit.o

# target to build an object file
src/ThickScintHit.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ThickScintHit.cc.o
.PHONY : src/ThickScintHit.cc.o

src/ThickScintHit.i: src/ThickScintHit.cc.i
.PHONY : src/ThickScintHit.i

# target to preprocess a source file
src/ThickScintHit.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ThickScintHit.cc.i
.PHONY : src/ThickScintHit.cc.i

src/ThickScintHit.s: src/ThickScintHit.cc.s
.PHONY : src/ThickScintHit.s

# target to generate assembly for a file
src/ThickScintHit.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ThickScintHit.cc.s
.PHONY : src/ThickScintHit.cc.s

src/ThickScintSD.o: src/ThickScintSD.cc.o
.PHONY : src/ThickScintSD.o

# target to build an object file
src/ThickScintSD.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ThickScintSD.cc.o
.PHONY : src/ThickScintSD.cc.o

src/ThickScintSD.i: src/ThickScintSD.cc.i
.PHONY : src/ThickScintSD.i

# target to preprocess a source file
src/ThickScintSD.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ThickScintSD.cc.i
.PHONY : src/ThickScintSD.cc.i

src/ThickScintSD.s: src/ThickScintSD.cc.s
.PHONY : src/ThickScintSD.s

# target to generate assembly for a file
src/ThickScintSD.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ThickScintSD.cc.s
.PHONY : src/ThickScintSD.cc.s

src/ThinScintHit.o: src/ThinScintHit.cc.o
.PHONY : src/ThinScintHit.o

# target to build an object file
src/ThinScintHit.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ThinScintHit.cc.o
.PHONY : src/ThinScintHit.cc.o

src/ThinScintHit.i: src/ThinScintHit.cc.i
.PHONY : src/ThinScintHit.i

# target to preprocess a source file
src/ThinScintHit.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ThinScintHit.cc.i
.PHONY : src/ThinScintHit.cc.i

src/ThinScintHit.s: src/ThinScintHit.cc.s
.PHONY : src/ThinScintHit.s

# target to generate assembly for a file
src/ThinScintHit.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ThinScintHit.cc.s
.PHONY : src/ThinScintHit.cc.s

src/ThinScintSD.o: src/ThinScintSD.cc.o
.PHONY : src/ThinScintSD.o

# target to build an object file
src/ThinScintSD.cc.o:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ThinScintSD.cc.o
.PHONY : src/ThinScintSD.cc.o

src/ThinScintSD.i: src/ThinScintSD.cc.i
.PHONY : src/ThinScintSD.i

# target to preprocess a source file
src/ThinScintSD.cc.i:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ThinScintSD.cc.i
.PHONY : src/ThinScintSD.cc.i

src/ThinScintSD.s: src/ThinScintSD.cc.s
.PHONY : src/ThinScintSD.s

# target to generate assembly for a file
src/ThinScintSD.cc.s:
	$(MAKE) -f CMakeFiles/exampleN06.dir/build.make CMakeFiles/exampleN06.dir/src/ThinScintSD.cc.s
.PHONY : src/ThinScintSD.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... N06"
	@echo "... edit_cache"
	@echo "... exampleN06"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... exampleN06.o"
	@echo "... exampleN06.i"
	@echo "... exampleN06.s"
	@echo "... src/CsI_SD.o"
	@echo "... src/CsI_SD.i"
	@echo "... src/CsI_SD.s"
	@echo "... src/CsI_SDHit.o"
	@echo "... src/CsI_SDHit.i"
	@echo "... src/CsI_SDHit.s"
	@echo "... src/EventAction.o"
	@echo "... src/EventAction.i"
	@echo "... src/EventAction.s"
	@echo "... src/ExN06DetectorConstruction.o"
	@echo "... src/ExN06DetectorConstruction.i"
	@echo "... src/ExN06DetectorConstruction.s"
	@echo "... src/ExN06EventAction.o"
	@echo "... src/ExN06EventAction.i"
	@echo "... src/ExN06EventAction.s"
	@echo "... src/ExN06PMTHit.o"
	@echo "... src/ExN06PMTHit.i"
	@echo "... src/ExN06PMTHit.s"
	@echo "... src/ExN06PMTSD.o"
	@echo "... src/ExN06PMTSD.i"
	@echo "... src/ExN06PMTSD.s"
	@echo "... src/ExN06PhysicListMessenger.o"
	@echo "... src/ExN06PhysicListMessenger.i"
	@echo "... src/ExN06PhysicListMessenger.s"
	@echo "... src/ExN06PhysicsList.o"
	@echo "... src/ExN06PhysicsList.i"
	@echo "... src/ExN06PhysicsList.s"
	@echo "... src/ExN06PrimaryGeneratorAction.o"
	@echo "... src/ExN06PrimaryGeneratorAction.i"
	@echo "... src/ExN06PrimaryGeneratorAction.s"
	@echo "... src/ExN06PrimaryGeneratorMessenger.o"
	@echo "... src/ExN06PrimaryGeneratorMessenger.i"
	@echo "... src/ExN06PrimaryGeneratorMessenger.s"
	@echo "... src/ExN06RunAction.o"
	@echo "... src/ExN06RunAction.i"
	@echo "... src/ExN06RunAction.s"
	@echo "... src/ExN06StackingAction.o"
	@echo "... src/ExN06StackingAction.i"
	@echo "... src/ExN06StackingAction.s"
	@echo "... src/ExN06SteppingVerbose.o"
	@echo "... src/ExN06SteppingVerbose.i"
	@echo "... src/ExN06SteppingVerbose.s"
	@echo "... src/ExN06UserEventInformation.o"
	@echo "... src/ExN06UserEventInformation.i"
	@echo "... src/ExN06UserEventInformation.s"
	@echo "... src/Si_SD.o"
	@echo "... src/Si_SD.i"
	@echo "... src/Si_SD.s"
	@echo "... src/Si_SDHit.o"
	@echo "... src/Si_SDHit.i"
	@echo "... src/Si_SDHit.s"
	@echo "... src/ThickScintHit.o"
	@echo "... src/ThickScintHit.i"
	@echo "... src/ThickScintHit.s"
	@echo "... src/ThickScintSD.o"
	@echo "... src/ThickScintSD.i"
	@echo "... src/ThickScintSD.s"
	@echo "... src/ThinScintHit.o"
	@echo "... src/ThinScintHit.i"
	@echo "... src/ThinScintHit.s"
	@echo "... src/ThinScintSD.o"
	@echo "... src/ThinScintSD.i"
	@echo "... src/ThinScintSD.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

